import type { SmsCampaign } from '../types/sms.types'
import type { EmailCampaign } from '../types/email.types'

export const mockSmsCampaigns: SmsCampaign[] = [
  {
    id: 1,
    tenant_id: 1,
    created_by: null,
    name: 'Promo Vodacom Avril',
    message: 'Bénéficiez de 20% de réduction ce mois-ci ! Code : BIAR20',
    sender_id: 'BIAR',
    status: 'sent',
    scheduled_at: null,
    sent_at: '2026-04-01T11:30:00Z',
    total_recipients: 5000,
    total_sent: 5000,
    total_delivered: 4820,
    total_failed: 180,
    total_undelivered: 0,
    created_at: '2026-04-01T10:00:00Z',
    updated_at: '2026-04-01T11:30:00Z',
    deleted_at: null,
  },
  {
    id: 2,
    tenant_id: 1,
    created_by: null,
    name: 'OTP Connexion',
    message: 'Votre code de vérification : {{code}}. Valide 5 min.',
    sender_id: 'BIARAUTH',
    status: 'draft',
    scheduled_at: null,
    sent_at: null,
    total_recipients: 0,
    total_sent: 0,
    total_delivered: 0,
    total_failed: 0,
    total_undelivered: 0,
    created_at: '2026-04-05T09:00:00Z',
    updated_at: '2026-04-05T09:00:00Z',
    deleted_at: null,
  },
]

export const mockEmailCampaigns: EmailCampaign[] = [
  {
    id: 1,
    tenantId: 1,
    name: 'Newsletter Avril 2026',
    subject: 'Nouveautés BIAR Group — Avril 2026',
    fromName: 'BIAR Group Africa',
    fromEmail: 'info@biargroup.cd',
    replyTo: null,
    templateId: 1,
    htmlBody: '<h1>Bonjour</h1>',
    status: 'completed',
    scheduledAt: null,
    sentCount: 1200,
    openCount: 480,
    clickCount: 96,
    bounceCount: 24,
    totalRecipients: 1200,
    createdAt: '2026-04-01T08:00:00Z',
  },
]
